service: 'walmart-address'

provider:
  name: aws
  runtime: java11

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-south-1'}

  #Allows dynamodb table to be queried with action, and many more among others
  iamRoleStatements:
    -
      Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchGetItem
        - dynamodb:BatchWriteItem
      Resource:
        - !GetAtt WalmartAddressDynamoDBTable.Arn
        - arn:aws:dynamodb:ap-south-1:425380566961:table/walmart-address/index/walmart-address-secondaryIndex
    # added for enabling xray tracing of the service
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource:
        - "*"

custom:
  names:
    dynamodb:
      address: ${self:service}

functions:
    get:
      tracing: true #allows for generating x-ray traces for below function invocation
      handler: com.serverless.AddressHandler::getAddresses
      events:
        - httpApi:
            method: GET
            path: /v1/{accountId}/addresses
        - httpApi:
            method: GET
            path: /v1/{accountId}/address/{addressId}
    post:
      tracing: true
      handler: com.serverless.AddressHandler::addAddress
      events:
        - httpApi:
            method: POST
            path: /v1/{accountId}/addAddress
    delete:
      tracing: true
      handler: com.serverless.AddressHandler::deleteAddress
      events:
        - httpApi:
            method: DELETE
            path: /v1/delete/{accountId}/address/{addressId}

package:
  artifact: target/walmart-${opt:stage}.jar

resources:
    - ${file(template.yml)}

plugins:
  - serverless-plugin-tracing